### ISSUE TITLE
Push notification service

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#263]
Think of a simple implementation of GCM a like service which enables us to use push notifications without relying on the play services library. This would be a nice fix for #226

This would include research on possible protocols like XMPP or similar which save on bandwidth and battery usage.

**Comment by nilstk** [comment]
An issue is that this service will consume more energy for sure, since it's not possible to disable Google's services in general. Also their services are highly optimized to consume as less battery as possible. Nevertheless a possible option might be to use some sort of polling solution in case that the GCM services are not available (e.g. library not included / F-Droid release)

**Comment by kordianbruck** [comment]
@nilstk the idea is to implement such a power saving push service on the server. Whatsapp as well as FB messenger don't use gcm but rather have their own implementation of a keepalive socket. There is a [open source implementation like this](http://zeromq.org/)

If you don't require the services in your app they won't start in the background when the app starts.

**Comment by kordianbruck** [comment]
This is not feasable at the moment and we just moved to firebase - so closed for now.
