### ISSUE TITLE
Creating a fancy demo video 

### ISSUE THREAD

**Issue by TCA-Team** [TCA-Team/TumCampusApp#272]
... like our colleques from the Windows version 
https://www.youtube.com/watch?v=kCNvUT-knrE

---> Watch out for req. licenses regarding music and/or pictures !

**Comment by zenosewald** [comment]
Hi there, 
I would like to work/contribute on this subject. Is there a workgroup?

**Comment by kordianbruck** [comment]
We have some videos from the current new features but not really a full feature video. If you can create something fancy - it would be nice.

No, there is no demo user - you need to use the offical LRZ/TUM ID

**Comment by zenosewald** [comment]
Do you mind sharing the videos that already exist?

**Comment by kordianbruck** [comment]
@Carlinho89 @arash-a2k @enricogigantiello would it be okey with you guys to share those? Can you upload them to some hoster possibly?

**Comment by arash-a2k** [comment]
For me is OK. @kordianbruck I shared the videos, which were on our Google Drive to you.

**Comment by kordianbruck** [comment]
@zenosewald here are the videos then: 
* https://drive.google.com/file/d/0B8HWq2CaV01YaU1vU2w1V0ZsQVE/view?invite=COuFu8YH
* https://drive.google.com/file/d/0BzJIFOVW4P5DVEl0WVRvYUJ1eG8/view?invite=CKiZ1JAI
* https://drive.google.com/file/d/0B1Urit64i3nsTlpWWko3MmFKTFU/view?invite=CKOCh9sL
* https://drive.google.com/file/d/0BzJIFOVW4P5DTzNjb2l6NDhON0k/view?invite=CLyBxPQD

**Comment by kordianbruck** [comment]
@zenosewald have you been able to create something?

**Comment by zenosewald** [comment]
Hi, due to the limitations I momentanly have as a freshman (+semester
holidays) I am not able to use all features of the app itself. Because of
that I wanted to wait until I can use them all to crate the screen
recordings. (That's why I asked for the test account...)
So far I made some greenscreen animations in order to use them with the
recordings.

Kordian Bruck <notifications@github.com> schrieb am Mo., 7. Sep. 2015 20:40:

**Comment by kordianbruck** [comment]
@zenosewald so when are you getting an account then? Maybe we can set something up in a hangout. Write me a mail, so we can organize it.

**Comment by nilstk** [comment]
Any news here? Maybe we can get a promotion video ready till summer term? Don't forget that it should be a fancy one. Maybe include interviews with users on features they like, add initial tutorials with it,...

**Comment by zenosewald** [comment]
Hi, I'm sorry; I've had further problems running the app and so I don't think I'm the choice to record and compose the video... It's running a bit buggy at some point; probably the problem of my older android device... On top I haven't got Lollipop. And I think for a modern video the recordings should be based on an application running on Lollipop.
Due to that I'm not able to create a video so far; and don't think I can do this next time...
But there are some green-screen-templates and end-transitions you could use.

**Comment by anselm92** [comment]
- Always late to lectures? Not with TCA
- Don't know what to eat? 
- Can't find the room
- Lost in TUM?
- Wanna show your parents your grades?
- Don't know what you're watching? 
- You want to stay up to date what's happening at TUM?
- want to stay home but know what's going on in the lecture, use chat

**Comment by pfent** [comment]
[Spei](https://de.wiktionary.org/wiki/speien) exzellent mit der TUM Campus App :joy:

**Comment by kordianbruck** [comment]
ToDo
- [ ] Sound from nextcloud
- [ ] App rumspielen aus dem Video schneiden (den Anfang)
- [ ] Neues Video aus der MI Magistrale (60fps, 1080p, von unten nach oben?)
- [ ] Letzte Szene: mehr zentriert
- [ ] Andere Clips für den Anfang (miasantum, innenstadt campus, etc.)
