### ISSUE TITLE
Integrate WiFi coverage maps into campus maps and use the TCA to measure the signal strength

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#285]
The following website offers examples on how these maps might look like http://opensignal.com/

The idea is to integrate it in the TCA to aqquire live data on the signal strength of WiFi networks (e.g. eduroam) at various positions and collect everything in a map on a server.

For instance it might be of interest to someone to find the best spot in the university park with sufficient WiFi coverage without the hassle to run around and look for a signal boost. In addition it might help the administration to discover places that require better WiFi coverage.

**Comment by aserhany** [comment]
@nilstk, @kordianbruck , @pfent , @mhmadayad: we have downloaded the opensignal app and tested their developers api today and seen that the signal strength data in the coverage map are only for mobile operators and not for Wifi-connections. The API provides the following two types of data:
1. Network status (only for mobile operators)
2. Tower information
Source: http://developer.opensignal.com/towerinfo/

So for monitoring Eduroam connection quality opensignal might not be a suitable solution. 

However, we were thinking we can give it a try the similar idea for Wifi-connection with the following approach:
Given the fact that the indoor positioning is still unaccurate and subject of research, we were thinking we can use the physical routers' positions in TUM campuses (maybe the university can help in that). We can then measure the Wifi-speed of a specific router as follows:
1. Either: The uni sys. administration can provide such data in real time 
2. OR: we can use the average of the wifi-connection speed test of the given router based on TCA measurements of the app users, who are connected to this specific router in real time. The problem here would be that not everyone connected to the specific router has the TCA. 

After exceeding a specific threshold, we can say that a given router is currently overloaded for example and mark the its coverage area as red on the map. The TCA user can then look for the green spots on the map.

We are Looking forward to your opinion.

**Comment by aserhany** [comment]
@nilstk, @kordianbruck, @pfent, @mhmadayad :

Please ignore the last comment as we were thinking more about measuring the connection strength and not the coverage.

As mentioned previously:
"we have downloaded the opensignal app and tested their developers api today and seen that the signal strength data in the coverage map are only for mobile operators and not for Wifi-connections. The API provides the following two types of data:
1. Network status (only for mobile operators)
2. Tower information
Source: http://developer.opensignal.com/towerinfo/

So for monitoring Eduroam connection coverage opensignal might not be a suitable solution."

So If we are interested in measuring the coverage spots we should think of over solutions. If we are thinking of measuring the connection speed then you can have a look on the proposed approach in our  previous comment that you got per mail.

**Comment by nilstk** [comment]
Well, the idea was not to integrate opensignal itself, but adapter it (thinking about the map and show intensity of a signal) to WiFi. OpenSignal was just meant as an example on how it might look like.

Also the outdoor areas are of more interest here and I came up with that idea while walking behind the mechanical engineering building looking for a WiFi signal and a bench next to the lake. The WiFi coverage indoor is usually not bad, while it is - as you mentioned it - difficult to get the position. Instead outdoor you have GPS and other systems, which can help to create a detailed map of the WiFi signal strength between the buildungs and recreational areas.

**Comment by t2m4k1** [comment]
I'd be interested to tackle that together with @Biart95, since there are more Android Praktikum teams involved now i guess it makes sense to tackle the "big issues" together,

**Comment by kordianbruck** [comment]
@t2m4k1 great - maybe you can specify further, what exactly it will be you want to implement and how it benefits the users. Please do this directly here in the issue.

**Comment by t2m4k1** [comment]
Sure! My initial idea (ignoring indoor signal variance) would be to introduce a trigger like "wifi-connection established" and check for extra info like ssid. If it is possible to do that as a background service, it could then send a tuple of longitude/latitude string + signal strength to the server, e.g. by REST. Next step would be to implement database access in the backend with JPA and store this entity to the database. With:
https://developers.google.com/maps/documentation/javascript/heatmaplayer?hl=de
it could then be possible to implement a heatmap based on sql queries. This definitely will take some time since I've never programmed in JavaScript and I only did pretty basic JPA/Rest programming.

**Comment by pfent** [comment]
@t2m4k1 We can listen to broadcasts on Android, however the [CONNECTIVITY_ACTION](https://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html#MonitorChanges) is restricted to foreground usage, so we can't just specify it in the Manifest…

We probably want to register a `BroadcastReceiver` on `SCAN_RESULTS_AVAILABLE_ACTION` ([like so](http://stackoverflow.com/a/11439616)) and periodically issue [`WifiManager.startScan()`](https://developer.android.com/reference/android/net/wifi/WifiManager.html#startScan()) calls.

I also read an interesting article about [how apple does location services](https://appelsiini.net/2017/reverse-engineering-location-services/) today (you can probably skip the hexdumps…), maybe you also find it interesting.

**Comment by kordianbruck** [comment]
Android has limited what we can do in the background, this is no longer feasible to be implemented reasonably. Indoor location w/ GPS is very inaccurate and we are talking to people from Navis if we can use their SDK instead.
