### ISSUE TITLE
Quiz card feature for research works

### ISSUE THREAD

**Issue by nilstk** [TCA-Team/TumCampusApp#359]
Sometimes research works including bachelor's and master's theses require to ask a certain group of people (e.g. all ones with computer science background) a certain question, e.g. "Are you familiar with ARM assembler?" or other questions types (multiple choice etc.) to add some nice conclusions to their work.

The idea is to integrate such a feature in the TCA and add it to the default subscriptions, while the TCA itself may check certain requirements (e.g. question requires CS student). 

Furthermore the self-administration needs to be developed, since it should not be moderated by us, too. For instance each user may ask a question once a week and users may flag it as inappropriate, which deletes the questions after a few votes. 

In general the person asking the question may review the results all the time, before the question is removed after 30 days maybe.

**Comment by aserhany** [comment]
InApp High prio:
- [ ] my own questions display
- [ ] delete own questions

InApp low prio:
- [ ] Max of three questions per week

Server:
- [ ] Max of three questions per week
- [ ] Flagging
- [ ] Do not show already answered questions

**Comment by nilstk** [comment]
Possible improvements:
- add yes/no to answer screen (I assume yes is left side [light blue] and no right side [dark blue] atm.?)
- add remaining days or deletion date to a question (cf. proposed auto-deletion after 30 days)

**Comment by aserhany** [comment]
@nilstk : Thanks for the improvement suggestions. They were considered in our latest commits.

**Comment by nilstk** [comment]
Another idea, since I added the target faculties in a recent commercial manually:
What about adding an information string (short faculty name) regarding the target faculties to each question, e.g. CS, EDU, CHE, etc. at the place where I put "IT majors" atm
![survey](https://cloud.githubusercontent.com/assets/2790516/16271749/7ee3262a-389b-11e6-9703-d2528cd32c2d.png)

**Comment by aserhany** [comment]
@nilstk : it sounds useful to show the selected target faculties. However we should consider the two following points:

1. We think that in some cases it might not be that user friendly to show abbreviations of the selected target faculties inside the answers bar. For example when the user doesn't choose any target faculties which means that all faculties will automatically get selected fro the given question. Also the abbreviations might not look familiar to all users, specially non-German speaking students. 
What about adding one small round "i" button beside the question, that upon clicking shows the list of selected faculties with their full name? (in case of no selection of target faculties, then all faculties will be shown)

2. In order to do this task, the selected target faculties need to be added to the API. Currently the submitted own Questions don't get stored in the App but rather get fetched from the server and the selected faculties upon activity start.

**Comment by nilstk** [comment]
Yes, adding that information by introducing another information icon sounds like a great option. As mentioned I just came across the situation thinking about the questions and target faculties. Fortunately I found my notes again, but it would be great to have them in the app directly. In theory there are lots of options, like storing it locally of with the webservice. By default most people will use one instance of the TCA only, I guess (cf. local option). Probably I'm an exception using the emulator on my Desktop in addition. Nevertheless, you may go for the webservice version maybe instead. It's up to you guys...

**Comment by kordianbruck** [comment]
This has been implemented ages ago - why is this still open :thinking:
