### ISSUE TITLE
Add the Mensa Arcisstraße as a default mensa

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#409]
currently only Campus Garching, Campus Klinikum and Campus Weihenstephan are possible

**Comment by kordianbruck** [comment]
Arcisstraße is possible, if you have the GPS enabled. The selection of the default mensa is only for campi that have multiple mensas on their premises. As the "Innenstadt" only has one, there is nothing to select. As soon as a user moves inside the range, the startpage will display the correct mensa.

As this not always works, because the location is sometimes buggy, we might want to allow to manually set the campus at all times.

**Comment by pfent** [comment]
Oh well…
guess the default campus settings did not have any effect, due to a silly bug.

Fixed in 7ef5c323fb7c6dc7f474ed2a9c20f978593a76db
