### ISSUE TITLE
DAOize CacheManager

### ISSUE THREAD

**Issue by psukys** [TCA-Team/TumCampusApp#674]
CacheManager still uses `Cursor` queries.

Related: #544

**Comment by OliHalu** [comment]
@kordianbruck I would like to daoize the cache manager but building the latest master branch fails with error: 
error: package de.tum.in.tumcampus.app.databinding does not exist

**Comment by kordianbruck** [comment]
@OliHalu fixed. Thanks!

**Comment by kordianbruck** [comment]
Before migration this, please make sure, that using okhttp caching is not an option:
https://square.github.io/okhttp/3.x/okhttp/okhttp3/Cache.html

I think it does most of what we achieve with the cache manager.

**Comment by kordianbruck** [comment]
Please also make sure you check the related issue posted above. There is another link about caching there.

**Comment by OliHalu** [comment]
Allright...Well I guess okhttp sounds like it would make sense. Basically we should rewrite the existing methods to add/get data to/from cache etc. with okhttp approaches which respect the headers?

**Comment by kordianbruck** [comment]
@OliHalu yes - or even manually set the expire header, in case the server does not send one.

**Comment by OliHalu** [comment]
@kordianbruck Allright. So far I just daoized the CacheManager. I guess I can start trying to rework the caching on wednesday because of work today and tomorrow. I already had lots of thoughts about using okhttp for caching but I'm not sure how to properly approach this. As far as I know Okhttp handles everything from checking if the requested data is already in the cache, to cache it if not. So if we are using okhttp for caching do we still need the cache database?

**Comment by kordianbruck** [comment]
> So if we are using okhttp for caching do we still need the cache database?

no

**Comment by kordianbruck** [comment]
CacheManage has been removed <3
