### ISSUE TITLE
Configure picasso file caching

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#788]
Right now picasso is only caching in memory. On a restart of the app, it downloads the images for new.

The goal is to configure picasso to use a file cache, which will be cleared when the `Clear Cache` option is selected from the settings.

Read more:
* https://stackoverflow.com/questions/23978828/how-do-i-use-disk-caching-in-picasso
* https://github.com/square/picasso/issues/1154
* Related #674

**Comment by velev8** [comment]
Where can I find the class the student from #674 has worked on in Feb/March?

**Comment by kordianbruck** [comment]
@velev8 https://github.com/TCA-Team/TumCampusApp/blob/ebf4e176c1996a16283da641d2eee641ab62fa11/app/src/main/java/de/tum/in/tumcampusapp/utils/CacheManager.java

But this is about the Picasso library used in various places, not the CacheManager: https://github.com/TCA-Team/TumCampusApp/search?utf8=%E2%9C%93&q=picasso&type=

**Comment by pfent** [comment]
@kordianbruck I don't think that stackoverflow answer recommending to subclass Activity is particularely great.
[Google recommends against this](https://developer.android.com/reference/android/app/Application) and says to use a static singleton instead.

That singleton would then replace all `Picasso.get()` calls, which lazily initializes Picasso with that `setSingletonInstance()`, as discussed at that stackoverflow article

**Comment by kordianbruck** [comment]
@pfent great idea - if you can help @velev8 with how to setup that kotlin `object` (which is a singleton) that'd be great. Or maybe just post an example? :+1:

**Comment by pfent** [comment]
sure, @velev8 I created some TODOs for you, to get you up to speed:

- [ ] create a new working branch
- [ ] add a new singleton in the `utils` package, right besides the cache manager
an `object` as suggested probably won't work, because you need an application context for the builder.
I'd recommend [this approach](https://stackoverflow.com/questions/40398072/singleton-with-parameter-in-kotlin/45943282#45943282), which is basically copy :spaghetti: from the google samples, but feel free to use any other approach (including Java)
- [ ] adapt that code to properly initialize Picasso (see OC)
- [ ] replace all usages of `Picasso.get()` with our singleton
- [ ] don't forget to `git push`
- [ ] open up a Pull Request

**Comment by velev8** [comment]
Thank you so much @pfent !!!

**Comment by velev8** [comment]
Hi everyone, I chose a different route (configured Picasso in a subclass of Application instead of creating a new class)!

**Comment by kordianbruck** [comment]
@velev8 as Philipp has explained above, extending `Activity` is not a great move for reasons already mentioned. Please explain, why you chose your route, so we can understand why it is better than the previously described one.

**Comment by thellmund** [comment]
@kordianbruck Here’s my understanding: Google discourages this kind of usage: 
`MyApplication app = (MyApplication) getApplicationContext();`
`app.getMyAwesomeSingleton();`

What @velev8 is doing is initializing a Singleton in Application without adding any new member variables to the class. I find that to be the more elegant solution, preferable to replacing all usages of `Picasso.get()`.
