### ISSUE TITLE
How to test the app with a local test server

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#840]
When we add new API enpoints to the server, it would be helpful to be able to test the app in connection with a test server which is hosted on our local machine.

@schulzalexander and I tried some things but did not yet get it to work.

It would be nice to have some instructions on how to do that.

**Comment by schulzalexander** [comment]
or can we just merge dummy functions for now to the server, to get some kind of static return values, in order for the frontend to be able to implement the client's API fetching functions?

**Comment by kordianbruck** [comment]
@saileru a few aspects to checkout:
* make sure you are not using SSL for local development. So remove any http**s** from the URL
* Use your local Wifi IP, not your global / public IP
* Make sure your firewall is not blocking any requests
* Remove any pinning (certificatePinner) in `de.tum.in.tumcampusapp.api.app.Helper`
* Change the `API_HOSTNAME` in `Const.kt` to your IP and correct port with any appended Path.
* Make sure you setup the app through the wizard using already the locally configured server. Otherwise some features won't work (Chat).

Let me know if this helps with debugging locally.

**Comment by saileru** [comment]
@kordianbruck Thank you very much! Your tips really helped.

However, we still get errors like "Missing column in database" which cause the app to crash. Adding the columns manually seems to fix most of these problems.
Could it be that the databases in the repository are outdated?

**Comment by kordianbruck** [comment]
@saileru might very well be. We are still missing a proper migration setup in that regard.
