### ISSUE TITLE
Ticket Sale: Feedback Event Overview

### ISSUE THREAD

**Issue by saileru** [TCA-Team/TumCampusApp#895]
Please give us feedback how to improve the ticket sale UI

One point from the scrum meeting is:
The button to filter booked events is not intuitive -> replace by tabs/segmented view

![screenshot_20180612-142608](https://user-images.githubusercontent.com/12066533/41290405-14405f7e-6e4d-11e8-9938-5cc13922d752.png)
![screenshot_20180612-142522](https://user-images.githubusercontent.com/12066533/41290402-13e8831c-6e4d-11e8-88d7-1ef292acb6b8.png)
![screenshot_20180612-142615](https://user-images.githubusercontent.com/12066533/41290406-14824e7a-6e4d-11e8-9103-b10a3b019a64.png)

**Comment by kordianbruck** [comment]
* Yes, tabs definitely make more sense here. 
* I would default to bought tickets, in case there are any unredeemed ones. Otherwise show all events
* Menu Entry needs to be more descriptive: Veranstaltungen & Tickets / Events & Tickets ?
* Should we use a card view? 
* The elements should be separated a bit from each other
* Description & address do not need to be shown here
* Title below image & image full width?
* Activity Name should match the menu entry
* Is pull to refresh supported?

**Comment by Kailiangdong** [comment]
improved part of it in #912

**Comment by Kailiangdong** [comment]
No description text. No address.
