### ISSUE TITLE
Start animation in StartupActivity runs twice

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/TumCampusApp#907]
When opening the app, the animation in StartupActivity runs twice (at least on my device running Android P). 

Take a look: 
![ezgif-5-a7c08a4048](https://user-images.githubusercontent.com/11819826/41464241-ea35fbcc-7099-11e8-98c2-ab49644de90d.gif)

**Comment by kollerlukas** [comment]
I took a look into this issue.
It seems that the `DownloadService` is triggered twice with `Const.DOWNLOAD_ALL_FROM_EXTERNAL`. The first time from the `StartupActivity` with the `Const.APP_LAUNCHES` Intent and the second time trough  `MainActivity.downloadNewsAlert()` being called in `MainActivity.onCreate()`.
Consequently the registered BroadcastReceiver in `StartupActivity` recieves two completed-Broadcasts  from the `DownloadService`. Which then results in `StartupActivity.startApp()` being called twice.
This would explain why the animation runs twice.
Now I don't know why this issue isn't showing on non-Pie devices.

Since the `MainActivity.downloadNewsAlert()` call in `MainActivity.onCreate()` is redundant, removing this call fixes the issue.

**Comment by thellmund** [comment]
Fixed with #1061.
