### ISSUE TITLE
Ticket Sale: Admin - Check tickets offline

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#950]

**Comment by velev8** [comment]
1. TS-Ma-1: As a student, I want to have access to my tickets offline, so that I can show
them at the event even without internet connection.

The app should automatically download the QR code of purchased tickets, so that the student is
not dependent on an active internet connection when visiting the event. The data should
probably be saved in the internal storage of the device, e.g. described in
https://stackoverflow.com/questions/10962344/how-to-save-data-in-an-android-app.

**Comment by velev8** [comment]
_5. TS-Mi-5: As a cashier, I want to be able to check the validity of tickets offline, so that
even with technical problems or bad connection regarding the network the event can
continue._

The content of the ticket, which uniquely identifies the event and purchaser, is at the
transaction signed with a private key by the server. Therefore, the cashier can just use the
respective public key to check if the ticket content is valid and was actually generated by the
server. Since the public key is shared beforehand, this can also happen offline.

**Comment by schulzalexander** [comment]
Backend side done in [#43](https://github.com/kordianbruck/tca-backend/pull/43)

**Comment by saileru** [comment]
Transferred to TicketCheck Repository 
https://github.com/TCA-Team/TicketCheck/issues/6
