### ISSUE TITLE
Ticket Sale: Email after buying

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#951]

**Comment by velev8** [comment]
1. TS-Mi-1: As a student, I want to additionally receive an email containing my tickets, so
that I have a backup in case there is a problem with the app.
The server should send the user an email containing the ticket information.

**Comment by kordianbruck** [comment]
I think this is done, right? @schulzalexander

**Comment by schulzalexander** [comment]
Done in [#40](https://github.com/kordianbruck/tca-backend/pull/40)

**Comment by schulzalexander** [comment]
I just purchased a ticket and received the mail, but turns out it looks different than when I send it locally to myself:
<img width="634" alt="bildschirmfoto 2018-07-09 um 09 03 11" src="https://user-images.githubusercontent.com/30290755/42435632-6fd4cfae-8357-11e8-9b5e-8b88dbf581f7.png">

@kordianbruck can you maybe tweak the template a little and test it on the server? since the formatting is just right when I try it locally.
Maybe it's just that the default margin is different, and we have to add style="margin: 0;" in the **table** and **tr** elements.
Also we should change the double "<br/>"s to single ones.
